==== LandInfra and InfraGML

From the https://www.ogc.org/standard/infragml/[OGC website]:

____
The scope of the Land and Infrastructure (*LandInfra*) Conceptual Model
is land and civil engineering infrastructure facilities. Anticipated
subject areas include facilities, projects, alignment, road, railway,
survey, land features, land division, and "`wet`" infrastructure (storm
drainage, wastewater, and water distribution systems). The initial
release of this standard is targeted to support all of these except wet
infrastructure.
____

____
The OGC *InfraGML* Encoding Standard presents the
implementation-dependent, GML encoding of concepts supporting land and
civil engineering infrastructure facilities specified in the OGC Land
and Infrastructure Conceptual Model Standard (*LandInfra*), OGC
15-111r1. Conceptual model subject areas include land features,
facilities, projects, alignment, road, railway, survey (including
equipment, observations, and survey results), land division, and
condominiums. *InfraGML* is published as a multi-part standard.

* Part 0 addresses the Core Requirements Class from LandInfra.
* Part 1 addresses
the LandFeature Requirements Class from LandInfra.
* Part 2 addresses
the Facility and Project Requirements Classes from LandInfra.
* Part 3
addresses the Alignment Requirements Class from LandInfra.
* Part 4
addresses the Road and RoadCrossSection Requirements Classes from
LandInfra.
* Part 5 addresses the Railway Requirements Class from
LandInfra.
* Part 6 addresses the Survey, Equipment, Observations and
Survey Results Requirements Classes from LandInfra.
* Part 7 addresses
the Land Division and Condominium Requirements Classes from LandInfra.
____

===== Existing concepts proposed for reuse and extension for geotechnics

* <<Reusing-LandInfra-Alignment,InfraGML:Alignment>>
* <<Extending-Facility-and-FacilityPart,InfraGML:Facility and
FacilityPart>>

//section end fix
